<?php

return [
    'badwords'   => [
        '9nl.es',
        'ad.fly',
        'adfly',
        'branddeals',
        'ddos',
        'ddosing',
        'dos',
        '(dot)',
        'fag',
        'faggot',
        'fgt',
        'gamergate',
        'gamersgate',
        'niga',
        'nigga',
        'niggah',
        'niggar',
        'nigger',
        'nigguh',
        'peva',
        'rape',
        'raping',
        't.co.ua',
        'tinman',
    ],
];
